# Setup
title:               me@aranha
tagline:             '#'
description:         "Hi, I`m a cyber security researcher and encryption engineer. 
                      I love to build and break things to learn how they work. In my free time I play CTF
                      with the <a href='http://deadlock.team/'>Deadlock Team</a>."
                      # I currently work in a Brazilian 
                      # research center with research and development of security and applied encryption 
                      # softwares. Looking forward to taking on a new challenge and working with talented, 
                      # passionate and dedicated people.'
url:                 https://mattslv.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Matheus Aranha
  url:               https://mattslv.github.io
  email:             aranha.mss@gmail.com
  img:               avatar.png # add your photo
  about:             I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
  twitter:           mattslv
  facebook: # add your Facebook handle
  github:            mattslv # add your Github handle
  linkedin: # add your Linkedin handle

# Disqus
discus-identifier: mattslv # add your discus identifier

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
